### ISSUE TITLE
Slides do not react to the usual navigation shortcuts on startup

### ISSUE THREAD

**Issue by nthiery** [jupyterlab-contrib/rise#15]
## Description

Slides do not react to the usual navigation shortcuts on startup

## Reproduce

1. Follow jupyterlab-rise's  [binder link](https://mybinder.org/v2/gh/jupyterlab-contrib/rise/main?urlpath=lab/tree/examples/README.ipynb)
2. Slides appear in full screen
3. The usual shortcuts (space, arrow down, page down, ...) have no effect
4. Clic in a cell
5. Now the shortcuts function as usual

## Expected behavior

The shortcuts would immediately function as usual

## Context

Python package version: jupyterlab-rise 0.1.1

<details><summary>Extension version:</summary>
<pre>
jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter labextension list
JupyterLab v3.6.1
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.2 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyterlab-rise v0.1.0 enabled OK (python, jupyterlab_rise)
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.7.0 enabled OK (python, jupyter-resource-usage)

jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter server extension list
Config dir: /home/jovyan/.jupyter

Config dir: /srv/conda/envs/notebook/etc/jupyter
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage 0.7.0 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
      jupyter_server_fileid 0.6.0 OK
    jupyter_server_ydoc enabled
    - Validating jupyter_server_ydoc...
      jupyter_server_ydoc 0.6.1 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.6.1 OK
    jupyterlab_rise enabled
    - Validating jupyterlab_rise...
      jupyterlab_rise 0.1.1 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic 0.5.1 OK
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  OK
    jupyter_offlinenotebook enabled
    - Validating jupyter_offlinenotebook...
      jupyter_offlinenotebook  OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

- Operating System and its version: Ubuntu 22.04
- Browser and its version: Firefox 110 64 bits

<details><summary>Command Line Output</summary>
<pre>
N/A
</pre>
</details>

**Comment by fcollonval** [comment]
My guess is that the focus is given to the notebook document. So when the application look if a keyboard shortcut is hit, it does not match a keyboard shortcut CSS selector.

**Comment by hbcarlos** [comment]
> My guess is that the focus is given to the notebook document

The focus is given to the lumino widget that wraps the `iframe` instead of the `iframe` itself. To the `DocumentWidget<IFrame, INotebookModel>.content`.

**Comment by nthiery** [comment]
I confirm that it works smoothly now on my machine! Thanks @fcollonval  and @hbcarlos !
