### ISSUE TITLE
Open With -> Slides

### ISSUE THREAD

**Issue by nthiery** [jupyterlab-contrib/rise#17]
# Description

In the file browser, right click on a notebook, choose Open With and then Slides.

The notebook is immediately opened as a slide show, in the main panel.

# Context

Nothing but candy to save a bit time when opening slides in a rush at the
beginning of your course :-)

**Comment by hbcarlos** [comment]
Hi @nthiery. Could you extend this issue?

If I understood correctly, this feature already exists (it is currently broken). You can do `Open With` -> `rise`; see the screencast below.

[Screencast from 2023-07-20 14-01-03.webm](https://github.com/jupyterlab-contrib/rise/assets/26092748/9e2cf455-cba1-4453-8624-ee22fc6b91b3)
