### ISSUE TITLE
css not loaded because of MIME type mismatch

### ISSUE THREAD

**Issue by miguelmarco** [jupyterlab-contrib/rise#27]
## Description

If I run a local instance of jupyterlab with rise enabled, can't load custom `rise.css` or `notebookname.css` files. The console in my broser shows the error message: 

```
The resource from  “http://localhost:8888/files//rise.css” was blocked due to a MIME type mismatch (“text/html”) (X-Content-Type-Options: nosniff).
```

## Reproduce

1. Install `jupyterlab_rise`with pip
2. Create a simple notebook and `rise.css` file
3. show the notebook with rise

## Expected behavior

the rise presentation is decorated according to the rules in `rise.css`

## Context

- Python package version:

- Extension version: jupyterlab_rise 0.2.0
- Operating System and its version: Gentoo linux
- Browser and its version: firefox 102.9.0esr

**Comment by steff-mueller** [comment]
I noticed that `rise.css` gets loaded successfully if one puts the notebook and `rise.css` into a subdirectory instead of root. Otherwise, I get the same error.

**Comment by trevex** [comment]
Thanks @steff-mueller using a sub-folder is indeed a workaround.

Looks like the double-slash causes the issues. Manipulating the original request from the root folder to have a single `/` in the path will result in successfully returning the CSS.
