### ISSUE TITLE
jupyterlab-system-monitor renders [horribly] when rendering in skideshow mode

### ISSUE THREAD

**Issue by perllaghu** [jupyterlab-contrib/rise#4]
When displaying a notebook in "Slideshow" mode, the extension [jupyterlab-system-monitor](https://github.com/jtpio/jupyterlab-system-monitor) is included... and takes up a large amount of the display:

See https://photos.app.goo.gl/iPpsJY5rzQEnuVpT8

## Context

I'm running a jupyterlab docker image created thus:

```
FROM jupyter/minimal-notebook:2022-10-17

RUN pip install jupyterlab_rise  &&  mamba clean --all -f -y

RUN pip install jupyterlab-system-monitor  &&  mamba clean --all -f -y

WORKDIR $HOME
USER $NB_USER
```

The notebook is actually one I use to test `rise` in a service I run.... with more complex notebook images - so I realise the actual cells won't run :chuckle:

## Expectation

I would not have expected the extension to be included in the slide-show rendering

**Comment by martinRenou** [comment]
cc. @jtpio for awareness

**Comment by jtpio** [comment]
Thanks for the ping.

Wondering if this happens with other extensions that put widgets in the top area. 

Also I was hoping to move some of the functionalities of the `system-monitor` extension to the `jupyter-resource-usage` at some point to ease maintenance and consolidate the existing extension. Probably something to do after the JupyterLab 4 final release.

**Comment by perllaghu** [comment]
> Wondering if this happens with other extensions that put widgets in the top area.

Happy to try, if you can suggest one

**Comment by krassowski** [comment]
I believe this is a bug in jupyterlab-rise that I highlighted in my review: https://github.com/damianavila/RISE/pull/605#pullrequestreview-1014165248 and it is way worse for jupyterlab-citation-manager.

I dissected this in https://github.com/damianavila/RISE/pull/605#discussion_r903019798.
