### ISSUE TITLE
Code cells randomly don't render properly

### ISSUE THREAD

**Issue by sahra-marie** [jupyterlab-contrib/rise#8]
**Description**: In the slideshow code cells are shown randomly in a collapsed way. Only when clicking on them they expand.

![Collapsed](https://user-images.githubusercontent.com/93926203/216054385-c15a7f27-c168-43c0-bc87-a44ee88d9a72.jpg) ![Clicked](https://user-images.githubusercontent.com/93926203/216054902-9403b046-0669-45ea-9eaa-d1ac01bdbea9.jpg)

**Reproduce**: I couldn't find any interrelation with the selected slide type of the code cell and didn't manage to reproduce it on purpose yet, but it also happens with some code cells in the Binder example.

**Expected behavior**: Always show code cells and their content in expanded way.

**Comment by nthiery** [comment]
As another data point: I got the same issue.

Firefox 110.0 64bit on Ubuntu

Installation by pip in a mambaforge environment containing in particular:

<details>

```
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              4.12.0          py310hff52083_0    conda-forge
jupyter_server            1.23.5             pyhd8ed1ab_0    conda-forge
jupyterlab                3.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab-markup         1.0.1              pyhd8ed1ab_0    conda-forge
jupyterlab-myst           0.1.6              pyhd8ed1ab_0    conda-forge
jupyterlab-rise           0.1.0                    pypi_0    pypi
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.19.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
```

</details>

**Comment by joaquinvanschoren** [comment]
I get the same issue using the latest version of miniconda. 

I tried editing the styling in nbconvert/templates/reveal/ but this doesn't seem to have any effect. Which style templates are actually used?

**Comment by AnotherCodeArtist** [comment]
Just created a PR to fix this.
