### ISSUE TITLE
Digital sim card

### ISSUE THREAD

**Issue by jokerMANN1911** [jupyterlab-contrib/rise#90]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Python package version:

- Extension version:

- Operating System and its version: 
- Browser and its version: 

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Closing as spam
